### ISSUE TITLE
How can I package this app using electron-packager?

### ISSUE THREAD

**Issue by ammarrush** [MayGo/tockler#116]
I used electron-packager to create a package out of this repo. I ran the following command in the root folder:

`electron-packager . --overwrite --platform=darwin --arch=x64 --icon=client/src/assets/icons/zepto_icon.icns --prune=true --out=release-builds`

The app that is in the release folder, when I run it gives the following error:

```
Uncaught Exception:
Error: Cannot find module '/Users/ammarhassan/Zepto/zepto-desktop-tracking/release-builds/Zepto-darwin-x64/Zepto.app/Contents/Resources/app/index.js'
at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
at Object.<anonymous> (electron/js2c/browser_init.js:185:3470)
at Object../lib/browser/init.ts (electron/js2c/browser_init.js:185:3714)
at __webpack_require__ (electron/js2c/browser_init.js:1:128)
at electron/js2c/browser_init.js:1:1200
at electron/js2c/browser_init.js:1:1267
at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:277:7)
at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:219:10)
at loadNativeModule (internal/modules/cjs/helpers.js:24:9)
```

**Comment by MayGo** [comment]
Run the command in ./electron folder.
