### ISSUE TITLE
Error: The module 'DTraceProviderBindings.node' was compiled against a different Node.js version

### ISSUE THREAD

**Issue by hanselke** [MayGo/tockler#19]
noticied that yarn install rebuilds a couple of libraries. was getting some error with dtrace-provider about being built with incorrect version. I'm on nodejs 8.1

**Comment by MayGo** [comment]
I have node 7. There was a manual workaround for this error. But automatic fix is needed. Maybe update some dependencies.
Error should not break anything app related.

`Error: The module '/Users/maygo/_SOURCES/tockler/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/maygo/_SOURCES/tockler/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Object.<anonymous> (/Users/maygo/_SOURCES/tockler/node_modules/dtrace-provider/dtrace-provider.js:42:3)
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/maygo/_SOURCES/tockler/node_modules/electron/dist/Electron.app/Contents/Resources/el
ectron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/maygo/_SOURCES/tockler/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Object.<anonymous> (/Users/maygo/_SOURCES/tockler/node_modules/dtrace-provider/dtrace-provider.js:42:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/maygo/_SOURCES/tockler/node_modules/electron/dist/Electron.app/Contents/Resources/el
ectron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/maygo/_SOURCES/tockler/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Object.<anonymous> (/Users/maygo/_SOURCES/tockler/node_modules/dtrace-provider/dtrace-provider.js:42:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' }`

**Comment by MayGo** [comment]
should be bunyan problem. If problem rises to many times, then i will replace what logging library.
Remove node_modules and then do 
`yarn --ignore-optional`

**Comment by hanselke** [comment]
possible to switch to either node6 or node8? there is no lts support for node7

**Comment by MayGo** [comment]
I replace bunyan with electron-log. Its  in incomplete branch.
