### ISSUE TITLE
[Linux] `libva` error

### ISSUE THREAD

**Issue by evdcush** [MayGo/tockler#276]
`[3.21.18](https://github.com/MayGo/tockler/releases/tag/v3.21.18)`
I downloaded the AppImage for the [`3.21.18` release](https://github.com/MayGo/tockler/releases/tag/v3.21.18).

I encountered the following error:

```
$ ./Tockler-3.21.18.AppImage 
User dir is:/home/foo/.config/tockler
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
[1216422:0721/103617.291927:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
app is ready
```

**Comment by MayGo** [comment]
What was latest that worked for you? [3.21.12](https://github.com/MayGo/tockler/releases/tag/v3.21.12)?

**Comment by MayGo** [comment]
Quick googling about the error:
https://askubuntu.com/questions/1384489/error-while-running-spotify-libva-error-init-failed:
```
sudo apt-add-repository universe
sudo apt-get update
sudo apt-get install intel-media-driver
```

Perhaps that helps?

**Comment by evdcush** [comment]
Thank you for your prompt response @MayGo!

The `3.21.18` release was the first I ever tried this app.

I just tried `3.21.12`, received a similar error:

```
$ ./Tockler-3.21.12.AppImage 
User dir is:/home/foobar/.config/tockler
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
[31112:0721/171652.090826:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
17:16:52.450 › App errored in ready event: Error: The migration directory is corrupt, the following files are missing: 20221112_add_data_settings.js Error: The migration directory is corrupt, the following files are missing: 20221112_add_data_settings.js
    at validateMigrationList (/tmp/.mount_TockleOW8hTM/resources/app/node_modules/knex/lib/migrations/migrate/Migrator.js:564:11)
    at Migrator.latest (/tmp/.mount_TockleOW8hTM/resources/app/node_modules/knex/lib/migrations/migrate/Migrator.js:70:7)
app is ready
^CThis error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read properties of undefined (reading 'destroy')
    at Function.<anonymous> (/tmp/.mount_TockleOW8hTM/resources/app/dist/index.js:1:8472)
    at Generator.next (<anonymous>)
    at /tmp/.mount_TockleOW8hTM/resources/app/dist/index.js:1:7871
    at new Promise (<anonymous>)
    at i (/tmp/.mount_TockleOW8hTM/resources/app/dist/index.js:1:7616)
    at Function.destroy (/tmp/.mount_TockleOW8hTM/resources/app/dist/index.js:1:8417)
    at /tmp/.mount_TockleOW8hTM/resources/app/dist/index.js:1:19888
    at Generator.next (<anonymous>)
    at /tmp/.mount_TockleOW8hTM/resources/app/dist/index.js:1:19057
    at new Promise (<anonymous>)
(node:31060) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'destroy')
    at Function.<anonymous> (/tmp/.mount_TockleOW8hTM/resources/app/dist/index.js:1:8472)
    at Generator.next (<anonymous>)
    at /tmp/.mount_TockleOW8hTM/resources/app/dist/index.js:1:7871
    at new Promise (<anonymous>)
    at i (/tmp/.mount_TockleOW8hTM/resources/app/dist/index.js:1:7616)
    at Function.destroy (/tmp/.mount_TockleOW8hTM/resources/app/dist/index.js:1:8417)
    at /tmp/.mount_TockleOW8hTM/resources/app/dist/index.js:1:19888
    at Generator.next (<anonymous>)
    at /tmp/.mount_TockleOW8hTM/resources/app/dist/index.js:1:19057
    at new Promise (<anonymous>)
(Use `tockler --trace-warnings ...` to show where the warning was created)
(node:31060) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

I tried:

```
$ sudo apt-add-repository universe
'universe' distribution component is already enabled for all sources.
```

There is no `intel-media-driver` available.
`intel-media-va-driver` is available, and it was already installed.

**Comment by MayGo** [comment]
What linux distro are you using?

**Comment by evdcush** [comment]
```
screenfetch
                          ./+o+-       foobar@myhostname
                  yyyyy- -yyyyyy+      OS: Ubuntu 20.04 focal
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 5.15.0-76-generic
           .++ .:/++++++/-.+sss/`      Uptime: 4h 23m
         .:++o:  /++++++++/:--:/-      Packages: 2622
        o:+o+:++.`..```.-/oo+++++/     Shell: zsh 5.8
       .:+o:+o/.          `+sssoo+/    Resolution: 2240x1400
  .++/+:+oo+o:`             /sssooo.   DE: GNOME 3.36.5
 /+++//+:`oo+o               /::--:.   WM: Mutter
 \+/+o+++`o++o               ++////.   WM Theme: 
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Yaru [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: Yaru
        \+.++o+o``-````.:ohdhhhhh+     Font: Inter 11
         `:o+++ `ohhhhhhhhyo++os:      Disk: 88G / 491G (19%)
           .o:`.syhhhhhhh/.oo++o`      CPU: 12th Gen Intel Core i7-1270P @ 16x 4.8GHz [57.0°C]
               /osyyyyyyo++ooo+++/     GPU: Intel Corporation Device 46a6 (rev 0c)
                   ````` +oo+++o\:     RAM: 11415MiB / 47839MiB
                          `oo++.      

```

**Comment by MayGo** [comment]
Fixing specific linux disto problems is problematic for me

**Comment by MayGo** [comment]
Nice!
