### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by cesarve77** [MayGo/tockler#46]
I remove the app from my application Folder.
I close the app 

but when I restart is there

**Comment by MayGo** [comment]
You should not be able to remove app if it is still open.
So, maybe Tockler is actually running from somewhere else?

**Comment by MayGo** [comment]
You can find out where it is by opening Users & Groups and 'right' clicking on Tockler item and selecting Show in Finder:
<img width="554" alt="Screen Shot 2019-05-31 at 9 03 41 PM" src="https://user-images.githubusercontent.com/1929299/58725392-af1b5980-83e7-11e9-9bc2-4738597dfe10.png">

**Comment by cesarve77** [comment]
Im some way, I got 2 installations.
Now It fixed.

I'm going to tell you why I uninstall, may be it can help to new versions.
I really hate the terminal window opened, Im not sure If if a electron issue or tockler. anyway it is going to be a great app.

Goog Luck

**Comment by MayGo** [comment]
Glad you got that fixed. At some point, I will add a message that suggests adding the application to Applications folder.

Can you clarify terminnal window open problem? Which version?

**Comment by cesarve77** [comment]
When the app start it open a command window terminal with node running.
Im not sure about the version because I already uninstalled, but I download
the app on week ago from your repo.

I install it again and seems to be ok(no  command window opened)

**Comment by cesarve77** [comment]
I restarted the computer and there was the window terminal.
<img width="1679" alt="Screen Shot 2019-06-03 at 5 26 58 pm" src="https://user-images.githubusercontent.com/3970983/58783726-f4789a80-8624-11e9-8fd6-09e876d61c38.png">


see the terminal messages: 

there is a error:

```
Last login: Mon Jun  3 17:26:25 on console
/Applications/Tockler.app/Contents/MacOS/Tockler ; exit;
cmp:~ cesarramos$ /Applications/Tockler.app/Contents/MacOS/Tockler ; exit;
DB output path: /Users/cesarramos/Library/Application Support/Tockler/tracker.db
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
2019-06-03 17:26:36.239 Tockler[603:4569] *** WARNING: Textured window <AtomNSWindow: 0x7f88a1e77ed0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
{"name":"background-service","hostname":"cmp.local","pid":603,"level":30,"msg":"User Dir:/Users/cesarramos/Library/Application Support/Tockler","time":"2019-06-03T07:26:36.796Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":30,"msg":"Environment:undefined","time":"2019-06-03T07:26:36.798Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":30,"msg":"Running background service.","time":"2019-06-03T07:26:36.798Z","v":0}
Sending focus event: main-window-focus
Database synced.
No RUNNING_LOG_ITEM ref id
TIMELINE_LOAD_DAY_REQUEST 2019-06-02T14:00:00.000Z AppTrackItem
findAllFromDay AppTrackItem from:2019-06-02T14:00:00.000Z, to:Tue Jun 04 2019 00:00:00 GMT+1000 (AEST)
TIMELINE_LOAD_DAY_REQUEST 2019-06-02T14:00:00.000Z StatusTrackItem
findAllFromDay StatusTrackItem from:2019-06-02T14:00:00.000Z, to:Tue Jun 04 2019 00:00:00 GMT+1000 (AEST)
TIMELINE_LOAD_DAY_REQUEST 2019-06-02T14:00:00.000Z LogTrackItem
findAllFromDay LogTrackItem from:2019-06-02T14:00:00.000Z, to:Tue Jun 04 2019 00:00:00 GMT+1000 (AEST)
1
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:26:40.039Z","v":0}
Running assistive-access-el-capitan.osa
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:26:42.995Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:26:46.007Z","v":0}
Assistive access:   { Error: Command failed: osascript /Applications/Tockler.app/Contents/Resources/app/assistive-access-el-capitan.osa
/Applications/Tockler.app/Contents/Resources/app/assistive-access-el-capitan.osa:183:231: execution error: Error: unable to open database "/Library/Application Support/com.apple.TCC/TCC.db": unable to open database file (1)

    at ChildProcess.exithandler (child_process.js:214:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'osascript /Applications/Tockler.app/Contents/Resources/app/assistive-access-el-capitan.osa' } /Applications/Tockler.app/Contents/Resources/app/assistive-access-el-capitan.osa:183:231: execution error: Error: unable to open database "/Library/Application Support/com.apple.TCC/TCC.db": unable to open database file (1)

{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:26:49.019Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:26:52.046Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:26:55.042Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:26:58.188Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:27:01.118Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:27:04.222Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:27:07.163Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:27:10.234Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:27:13.243Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:27:16.339Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:27:19.315Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:27:22.303Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:27:25.308Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:27:28.323Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:27:31.357Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:27:34.347Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:27:37.364Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:27:40.391Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:27:43.406Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:27:46.422Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:27:49.458Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:27:52.470Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:27:55.497Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:27:58.502Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:28:01.505Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:28:04.542Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:28:07.558Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:28:10.581Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:28:13.590Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:28:16.615Z","v":0}
Show tray
No RUNNING_LOG_ITEM ref id
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:28:19.619Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:28:22.662Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:28:25.695Z","v":0}
Sending focus event: main-window-focus
TIMELINE_LOAD_DAY_REQUEST 2019-06-03 07:24:22.187 +00:00 AppTrackItem
findAllFromDay AppTrackItem from:2019-06-03 07:24:22.187 +00:00, to:Tue Jun 04 2019 07:24:22 GMT+1000 (AEST)
TIMELINE_LOAD_DAY_REQUEST 2019-06-03 07:24:22.187 +00:00 StatusTrackItem
findAllFromDay StatusTrackItem from:2019-06-03 07:24:22.187 +00:00, to:Tue Jun 04 2019 07:24:22 GMT+1000 (AEST)
TIMELINE_LOAD_DAY_REQUEST 2019-06-03 07:24:22.187 +00:00 LogTrackItem
findAllFromDay LogTrackItem from:2019-06-03 07:24:22.187 +00:00, to:Tue Jun 04 2019 07:24:22 GMT+1000 (AEST)
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:28:28.675Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:28:31.688Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:28:34.712Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:28:37.718Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:28:40.738Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:28:43.754Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:28:46.771Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:28:49.786Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:28:52.809Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:28:55.821Z","v":0}
TIMELINE_LOAD_DAY_REQUEST 2019-06-02T14:00:00.000Z AppTrackItem
findAllFromDay AppTrackItem from:2019-06-02T14:00:00.000Z, to:Tue Jun 04 2019 00:00:00 GMT+1000 (AEST)
TIMELINE_LOAD_DAY_REQUEST 2019-06-02T14:00:00.000Z StatusTrackItem
findAllFromDay StatusTrackItem from:2019-06-02T14:00:00.000Z, to:Tue Jun 04 2019 00:00:00 GMT+1000 (AEST)
TIMELINE_LOAD_DAY_REQUEST 2019-06-02T14:00:00.000Z LogTrackItem
findAllFromDay LogTrackItem from:2019-06-02T14:00:00.000Z, to:Tue Jun 04 2019 00:00:00 GMT+1000 (AEST)
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:28:58.834Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:29:01.854Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:29:04.879Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:29:07.889Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:29:10.906Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:29:13.931Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:29:16.934Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:29:20.002Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:29:22.977Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:29:25.988Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:29:29.000Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:29:32.016Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:29:35.056Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:29:38.039Z","v":0}
TIMELINE_LOAD_DAY_REQUEST 2019-06-02T14:00:00.000Z AppTrackItem
findAllFromDay AppTrackItem from:2019-06-02T14:00:00.000Z, to:Tue Jun 04 2019 00:00:00 GMT+1000 (AEST)
TIMELINE_LOAD_DAY_REQUEST 2019-06-02T14:00:00.000Z StatusTrackItem
findAllFromDay StatusTrackItem from:2019-06-02T14:00:00.000Z, to:Tue Jun 04 2019 00:00:00 GMT+1000 (AEST)
TIMELINE_LOAD_DAY_REQUEST 2019-06-02T14:00:00.000Z LogTrackItem
findAllFromDay LogTrackItem from:2019-06-02T14:00:00.000Z, to:Tue Jun 04 2019 00:00:00 GMT+1000 (AEST)
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:29:41.065Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:29:44.078Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:29:47.094Z","v":0}
{"name":"background-service","hostname":"cmp.local","pid":603,"level":50,"msg":"saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:119:168: execution error: Not authorised to send Apple events to System Events. (-1743)\n","time":"2019-06-03T07:29:50.133Z","v":0}
Closing window
BrowserWindow {
  _events: 
   { blur: [Function],
     focus: [ [Function], [Function] ],
     show: [Function: visibilityChanged],
     hide: [Function: visibilityChanged],
     minimize: [Function: visibilityChanged],
     maximize: [Function: visibilityChanged],
     restore: [Function: visibilityChanged],
     close: [Function: bound ] },
  _eventsCount: 8,
  devToolsWebContents: [Getter] }
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...12 completed.

[Process completed]

```

**Comment by MayGo** [comment]
Actually that's old version, perhaps https://github.com/MayGo/tockler/releases/tag/v3.4.13 works for you.
