### ISSUE TITLE
Data quit displaying after Electron 7 2/8/20

### ISSUE THREAD

**Issue by big610** [MayGo/tockler#65]
macOS After all the updates, I'm only able to see data backwards thru 2/7/20.
I would guess it was your change to Electron 8.
Sometimes I could go backwards & forwards with the arrow to get it engaged. 

Concerning the Automatic Updates, I stalled at 95%  attempting 3.9.2.
It would be less irritating if you switch to one banner to Update appears, then your next banner would read successful or Error at 95%.
In a case wanting to go back to an earlier version, when issues persist, an option to manually check for Updates & Auto Updates -User choice, to take auto or manual.

**Comment by MayGo** [comment]
Can you share some parts of tockler log from ~/Library/Logs/tockler/main.log
I reverted Electron back to 7 in 3.9.2.
Update messages can be irritating in case of failure. You can turn them off from settings.

**Comment by big610** [comment]
Electron 8 I was able to refresh the new days by going back and forth.
Anything else feel free to ask. Let me know if you want me to change versions & get you logs of that.

[2020-02-10 20:57:15.564] [info] Database dir is:/Users/User Name/Library/Application Support/tockler/tracker.db
[2020-02-10 20:57:15.731] [debug] Added Models AppSetting, Settings, TrackItem [function] class extends o.Model{} [function] class extends o.Model{get jsonData(){const e=this.getDataValue("jsonData");if(!e)return{};try{return JSON.parse(e)}catch(e){return{}}}set jsonData(e){try{this.setDataValue("jsonData",JSON.stringify(e))}catch(e){this.setDataValue("jsonData","{}")}}} [function] class extends o.Model{}
[2020-02-10 20:57:15.761] [info] Checking for updates.
[2020-02-10 20:57:15.762] [info] Checking for update
[2020-02-10 20:57:16.026] [info] Init main window events.
[2020-02-10 20:57:16.027] [info] Creating tray window.
[2020-02-10 20:57:16.028] [info] Database syncing....
[2020-02-10 20:57:16.593] [info] Executing (default): CREATE TABLE IF NOT EXISTS `TrackItems` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `app` VARCHAR(255), `taskName` VARCHAR(255), `title` VARCHAR(255), `color` VARCHAR(255), `beginDate` DATETIME, `endDate` DATETIME);
[2020-02-10 20:57:16.614] [info] Executing (default): PRAGMA INDEX_LIST(`TrackItems`)
[2020-02-10 20:57:16.639] [info] Executing (default): PRAGMA INDEX_INFO(`track_items_begin_date`)
[2020-02-10 20:57:16.640] [info] Executing (default): PRAGMA INDEX_INFO(`track_items_end_date`)
[2020-02-10 20:57:16.640] [info] Executing (default): PRAGMA INDEX_INFO(`track_items_task_name`)
[2020-02-10 20:57:18.647] [info] Database synced.
[2020-02-10 20:57:18.648] [info] Init app events.
[2020-02-10 20:57:18.653] [info] Setting openAtLogin to: undefined
[2020-02-10 20:57:18.739] [info] Restoring state.
[2020-02-10 20:57:18.745] [info] Executing (default): SELECT `id`, `name`, `jsonData` FROM `Settings` AS `a` WHERE `a`.`name` = 'RUNNING_LOG_ITEM' LIMIT 1;
[2020-02-10 20:57:18.759] [info] Executing (default): INSERT INTO `Settings` (`id`,`name`) VALUES (NULL,$1);
[2020-02-10 20:57:18.766] [info] Executing (default): SELECT `id`, `name`, `jsonData` FROM `Settings` AS `a` WHERE `a`.`name` = 'RUNNING_LOG_ITEM' LIMIT 1;
[2020-02-10 20:57:18.769] [error] App errored in ready event: {
  constructor: 'TypeError',
  stack: "TypeError: Cannot read property 'toJSON' of null\n" +
    '    at s.<anonymous> (/Applications/Tockler.app/Contents/Resources/app/dist/index.js:1:8533)\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at a (/Applications/Tockler.app/Contents/Resources/app/dist/index.js:1:7880)'
}
[2020-02-10 20:57:21.108] [info] Update for version 3.9.2 is not available (latest version: 3.9.2, downgrade is disallowed).
[2020-02-10 20:57:21.111] [debug] checkForUpdatesAndNotify called, downloadPromise is null
[2020-02-10 20:57:31.663] [info] Executing (default): SELECT `id`, `app`, `taskName`, `title`, `color`, `beginDate`, `endDate` FROM `TrackItems` AS `a` WHERE `a`.`taskName` = 'LogTrackItem' ORDER BY `a`.`beginDate` DESC LIMIT 200;
[2020-02-10 20:57:31.667] [info] Executing (default): SELECT `id`, `name`, `jsonData` FROM `Settings` AS `a` WHERE `a`.`name` = 'RUNNING_LOG_ITEM' LIMIT 1;
[2020-02-10 20:57:31.749] [info] Executing (default): INSERT INTO `Settings` (`id`,`name`) VALUES (NULL,$1);
[2020-02-10 20:57:31.757] [info] Executing (default): SELECT `id`, `name`, `jsonData` FROM `Settings` AS `a` WHERE `a`.`name` = 'RUNNING_LOG_ITEM' LIMIT 1;

**Comment by MayGo** [comment]
Can you try https://github.com/MayGo/tockler/releases/tag/v3.9.3

**Comment by big610** [comment]
Auto Update from 3.9.2 to 3.9.3 did not accept update. Manual download.

**Comment by MayGo** [comment]
Can you provide logs about that error? It should accept.

**Comment by big610** [comment]
Data showing. Big Log. You have it, I sent it the other way.

**Comment by MayGo** [comment]
In the logs I see that update was downloaded. After that you should have got a message, that new version will be installed when you exit and start Tockler again. I see that Tockler was exited and runned again. But was that when you manually installed 3.9.3? Or did you just exited and started?

**Comment by big610** [comment]
I received the banner, new version will be installed when you exit & start again.
Quit/Closed, re-opened, Version remained 3.9.2. Closed exited, manually used download to get to 3.9.3.

**Comment by MayGo** [comment]
Weirly i saw one exit and it said after that 3.8.3. Will check again.

**Comment by big610** [comment]
Sorry to bother you again, I can understand has been too much labor. 
I have had my computer on all day, I wide screened Tockler, thats when it began to track data right now, missed everything from when I pulled the logs up till now.
I also notice the backward & forward arrow's lag to move, is slow & a fight. I suggest to re-examine the last stable version, would it be 3.6.5 or 3.6.6? I'll stay on this version to help. My logs if I were to send are going to begin, when I wide screen opened Tockler, which is enabled sitting all the time in the Menu Bar. If your busy for awhile I'd like to go back to the best stable version to re-visit & test how it should be working. Your choice what ever you need me to do.

**Comment by MayGo** [comment]
So, to recap: 3.8.3 is working? Data is displaying?

`backward & forward arrow's lag to move, is slow & a fight.` you can make a gif or video about that. Picture says more than 1000 words :) . And let's make another issue about that.

**Comment by big610** [comment]
3.8.3 is not holding & storing the data. When you click on the upper right hand corner diagonal arrows it begins, then when you close out Tockler from displaying on desktop, stops & loses all retainment. Backward & Forward date arrows lags moving and pulling up past days data that was correctly retained is there. You should be able to replicate all of this. If not ask for a Quick Time Video, of what in particular you want to see.

**Comment by MayGo** [comment]
Closing of main Tockler window (tray icon is still displayed) should have no effect on data saving. I need to see your logs again.
Quick Time Video would be nice.

**Comment by MayGo** [comment]
Can you try 3.11.7? I tested on Windows 10 also.

**Comment by big610** [comment]
Tockler macOS 3.10.1 to 3.11.7 did not Auto update. Everything appears perfect with initial glances back & forward. You know how to do this now.

Other suggestion's:
Remove from front page, Stable 3.15 Versions.
Rename OS X to new Apple name macOS, that was changed in 2016 with beginning with Sierra.

So others can learn about Catalina, could you please state what Apple did that you had to overcome and learn. Open for speculation why Apple did this.

**Comment by MayGo** [comment]
Thanks for reminding me to fix Readme. 
Added improvement ticket: https://github.com/MayGo/tockler/issues/69

This issue was because of using [Sequelize ORM](https://sequelize.org/): sqlite3 DB was not syncing properly.  Refactored code and now are using [Objection.js](Objection.js) with [Knex JS](http://knexjs.org/) db migrations and queries.

**Comment by big610** [comment]
On Restart & Turn on from Power off... Notification Alert:
Tockler error
Error:
net::ERR-CONNECTION_TI...
I believe its been for all the Catalina versions, both Electrons, but needs re-confirmed, if both.

Added improvement ticket: #69. Needed to see current hour. 
When beginning new day with first activity, No data, just backwards, former day & beyond. Easily tested beginning after Midnight. 
When using for more than 2 hours, unable to see current hour, just backwards beginning with hour 2 and beyond. Thanks again.

**Comment by MayGo** [comment]
yeah, I haven't added any functionality that selects the next day after midnight. Will add this in #69
